# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: zh # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /:categories/:year/:month/:day/:title.html

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: 左遇
description: "左遇的个人博客"
keywords: 'technology,blog,netty'
author:
  name: 左遇
  job_title: Software Engineer
  location:
  email: 1461862234@qq.com
  social_links:
    - name: facebook
      url: 
    - name: github
      url: https://github.com/1461862234
    - name: instagram
      url:
    - name: linkedin
      url: 
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: '<style>img{border-radius: 50%;}</style><a href="/blog"><img src="http://139.199.25.193:8099/blog/image/head.jpg" style="width:220px"></a>'
  section2: <h1>左遇</h1>
  section3: <h2>软件工程师</h2>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: Copyright (c) 2011~2019 左遇 <a href="http://creativecommons.org/licenses/by-sa/4.0/">(CC BY-SA 4.0)</a>

disqus:
  shortname: 左遇
  public_key: 07eUSeijXrMdDdvqZUi4Begn3MMTKQyFoxI0cYWgzNXkngbn4gLUnCwayKVavOAI
google_tag_manager: 'UA-148477331-1' # e.g. 'GTM-KCQJXZ8F'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
